### ISSUE TITLE
android 8.0上锁屏可以正常记录轨迹吗

### ISSUE THREAD

**Issue by ljk761626336** [BLiYing/GaodeLiabrary#1]

**Comment by BLiYing** [comment]
@ljk761626336 和android系统版本无关，8.0上对定位有新的限制，测试过了，没影响。主要是小米手机神隐模式下有问题，关闭就没事。

**Comment by ljk761626336** [comment]
我也是使用的这种方式 在锁屏后或者app 在后台 是不行的   用你试试

**Comment by ljk761626336** [comment]
两步路户外助手这个软件 完全在后台定位  并且不被杀死  看是双服务   不知道怎么实现的  我使用双服务反而不行

**Comment by BLiYing** [comment]
> 我也是使用的这种方式 在锁屏后或者app 在后台 是不行的
