### ISSUE TITLE
你的联系方式，想请叫几个问题，我的微信18653223901

### ISSUE THREAD

**Issue by stanley20201** [BLiYing/GaodeLiabrary#3]

**Comment by zhin2929** [comment]
楼主你实现这个功能了吗

**Comment by stanley20201** [comment]
> 楼主你实现这个功能了吗

没有，你现在什么情况

**Comment by zhin2929** [comment]
> > 楼主你实现这个功能了吗
> 
> 没有，你现在什么情况

还在做呢，感觉不是很好弄。在考虑集成猎鹰。楼主加个qq963002549互相讨论一下吧

**Comment by zhin2929** [comment]
老哥，你这微信添加不了，隐私设置不可添加吧

**Comment by BLiYing** [comment]
这里只是提供一种思路。1.如何实时采集数据点（高德地图可以换成其他地图采集方式）；2.如何实现后台保活（锁屏和后台都可持续定位而不会被app误杀）。
